export const STEP_KEY = "onboardingStep";

export const ONBOARDING_STEP = {
    NEEDS_AGREEMENT: "NEEDS_AGREEMENT",
    NEEDS_ONBOARDING: "NEEDS_ONBOARDING",
    NEEDS_MARKETING: "NEEDS_MARKETING",
    COMPLETED: "COMPLETED",
};
